baseURL = "https://kubernetes-arm.com/"
languageCode = "en-us"
title = ""
theme = "minimal"
publishDir = "docs/"

[taxonomies]
    author = "authors"
    tag = "tags"
    category = "categories"

[params]
    description = "Kubernetes ARM"
    githubUsername = "kubernetes-arm"
    accent = "gray"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "rust"]
    copyright = "© Kubernetes ARM Contributors - 2020"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "https://github.com/orgs/kubernetes-arm/projects"
    name = "Projects"
    weight = 4

[[menu.icon]]
    url = "https://github.com/kubernetes-arm/"
    name = "github"
    weight = 5

[[menu.icon]]
    url = "mailto:info@kubernetes-arm.com"
    name = "envelope-o"
    weight = 6
